name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env: 
  DB_HOST = ${{secrets.DB_HOST}}
  JWT_SECRET = ${{secrets.jwt_secret}}
  MAILER_USER = ${{secrets.mailer_user}}
  MAILER_PASSWORD = ${{secrets.mailer_password}}
  NODE_ENV = ${{secrets.node_env}}

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test
